#!/usr/bin/python

print("This program will test the relays")
print(" -- uses gpio pins 23,8,12,21 -- ")
print(" each will turn on one after the other")
print(" until all are lit, then they'll start")
print(" to turn off one after the other.")
print("")
print("note- all on or all off relates to")
print("the internal relays not the socket")
print("this is dependent on the wiring of")
print("the relays, i.e. normally open or closed")
print("")
print("The sequence will repeat five times")
from time import sleep
import wiringpi
wiringpi.wiringPiSetupGpio()

wiringpi.pinMode(23, 1)
wiringpi.pinMode(8, 1)
wiringpi.pinMode(12, 1)
wiringpi.pinMode(21, 1)
for x in range(1, 5):
    print x
    wiringpi.digitalWrite(23, 1)
    sleep(2)
    wiringpi.digitalWrite(8, 1)
    sleep(2)
    wiringpi.digitalWrite(12, 1)
    sleep(2)
    wiringpi.digitalWrite(21, 1)
    sleep(2)
    print("all should be on")
    wiringpi.digitalWrite(23, 0)
    sleep(2)
    wiringpi.digitalWrite(8, 0)
    sleep(2)
    wiringpi.digitalWrite(12, 0)
    sleep(2)
    wiringpi.digitalWrite(21, 0)
    sleep(2)
    print("all should be off")